name: Check

on:
  pull_request: # Check Pull Requests

  push:
    branches:
      - main # Check branch after merge

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci --quiet --no-progress

      - name: Lint
        run: ./node_modules/.bin/gulp lint

      - name: Build bundle
        run: ./node_modules/.bin/gulp bundle

  finish:
    name: Finish
    if: github.event_name == 'pull_request'
    needs: # Should be last
      - "check"
    uses: playframework/.github/.github/workflows/rtm.yml@v2
