name: Publish

on:
  push:
    tags: ["**"] # Releases

jobs:
  publish-artifacts:
    name: "Release Play Antora UI"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci --quiet --no-progress

      - name: Build bundle
        run: ./node_modules/.bin/gulp bundle

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: build/ui-bundle.zip
